// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

const environment = env('ENVIRONMENT') ?? env('NODE_ENV') ?? 'dev';
const dbUrl =
  environment === 'prod' || environment === 'stag' ? env('DATABASE_URL') : 'postgresql://postgres:devpassword@localhost:5432/edc_portal'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: dbUrl,
  },
});
