// This file was generated by Prisma and assumes you have installed prisma.
import { defineConfig, env } from 'prisma/config';

process.loadEnvFile();

const environment =
  process.env.ENVIRONMENT ?? process.env.NODE_ENV ?? 'dev';
const dbUrl =
  environment === 'prod' || environment === 'stag'
    ? env('DATABASE_URL')
    : env('LOCAL_DATABASE_URL');

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: dbUrl,
  },
});
